---
downloads: ~/.ansible-downloads/
ohmyzsh_script: "sh \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
 - TV
 - 'Mensajes'
 - 'Mail'
 - 'Fotos'
 - 'Freeform'
 - 'Mapas'
 - 'Música'
 - 'Notas'
 - 'Recordatorios'
 - Podcasts
 - 'App Store'
 - 'FaceTime'
 - Maps
dockitems_persist:
 - name: "Obsidian"
   path: "/Applications/Obsidian.app/"
   pos: 3
 - name: "Visual Studio Code"
   path: "/Applications/Visual Studio Code.app/"
   pos: 4
 - name: "Bitwarden"
   path: "/Applications/Bitwarden.app/"
   pos: 5
 - name: "iTerm"
   path: "/Applications/iTerm.app/"
   pos: 6
 - name: "Microsoft Outlook"
   path: "/Applications/Microsoft Outlook.app/"
   pos: 7
 - name: "Microsoft Teams"
   path: "/Applications/Microsoft Teams.app/"
   pos: 8
 - name: "Spotify"
   path: "/Applications/Spotify.app/"
   pos: 9
 - name: "Firefox"
   path: "/Applications/Firefox.app/"
   pos: 10
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app/"
   pos: 11
 - name: "DuckDuckGo"
   path: "/Applications/DuckDuckGo.app/"
   pos: 12
 - name: "Safari"
   path: "/Applications/Safari.app/"
   pos: 13
 - name: "Tor"
   path: "/Applications/Tor Browser.app/"
   pos: 14
 - name: "Cyberduck"
   path: "/Applications/Cyberduck.app/"
   pos: 15
 - name: "WhatsApp"
   path: "/Applications/WhatsApp.app/"
   pos: 16
 - name: "AutoFirma"
   path: "/Applications/AutoFirma.app/"
   pos: 17
 - name: "LICEcap"
   path: "/Applications/LICEcap.app/"
   pos: 18

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/mordonez/mydotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - act
  - autoconf
  - bash-completion
  - gettext
  - ffmpeg
  - git
  - gitleaks
  - gh
  - gpg
  - httpie
  - iperf
  - openjdk
  - jmeter
  - jq
  - libevent
  - postman
  - llm
  - sqlite
  - nmap
  - node
  - rclone
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - appcleaner
  - autofirma
  - brave-browser
  - burp-suite
  - chromedriver
  - cyberduck
  - bitwarden
  - docker
  - duckduckgo
  - dropbox
  - firefox
  - font-fira-code
  - google-chrome
  - google-drive
  - licecap
  - sequel-ace
  - slack
  - sublime-text
  - iterm2
  - macpass
  - ngrok
  - owasp-zap
  - zettlr
  - microsoft-auto-update
  - microsoft-excel
  - microsoft-outlook
  - microsoft-powerpoint
  - microsoft-teams
  - microsoft-word
  - lando
  - obsidian
  - onedrive
  - owasp-zap
  - kindle
  - postman
  - rectangle
  - mitmproxy
  - spotify
  - sublime-text
  - the-unarchiver
  - vlc
  - utm
  - tor-browser
  - visual-studio-code
  - whatsapp
  - youtube-to-mp3
# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: corepack


# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

custom_script: "~/mac-dev-playbook-files/.ohmyzsh"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: 
  -  /Users/mordonez/mac-dev-playbook-files/tasks/*.yml
